### PR TITLE
Fix #346 - Transformer's transform method does not account for settings

### LINKED ISSUE #346: Transformer's transform method does not account for settings
# Steps required to reproduce the problem

1. Use a set of rules that include Analytics or Ads settings
2. Create instant article markup using the [Transformer::transform](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Transformer/Transformer.php#L285), instead of [Transformer::transformString](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Transformer/Transformer.php#L235)

# Expected Result
The markup includes the corresponding Analytics and/or Ads code

# Actual Result
The markup does not include the corresponding Analytics and/or Ads code because `transform` does not call `handleTransformationSettings`.

Note: To repro, replace `transformString` with `transform` in `SimpleTransformerTest::testSelfTransformerContent` and run the tests (`composer test`).

### PR DESCRIPTION
**Pull request by diegoquinteiro**
This PR

* [x] Fixes the `Transformer::transform` method to use the transformationSettings the same way as `Transformer::transformString`

Fixes #346

### CODE REVIEW

File: src/Facebook/InstantArticles/Transformer/Transformer.php [hunk 1]
```diff
@@ -375,6 +374,10 @@ public function transform($context, $node)
             }
         }
 
+        if ($is_top_of_recursion_stack) {
+          $context = $this->handleTransformationSettings($context);
```
Comment (everton-rosario) [inline src/Facebook/InstantArticles/Transformer/Transformer.php]: Identation issue. Add 2 more spaces here. 💅
